### ISSUE TITLE
Meters instead of feet

### ISSUE THREAD

**Issue by mlenser** [mlenser/roll20-character-sheets#106]

**Comment by mlenser** [comment]
@Alzam01 this is likely next on my list FYI. Finally got the translations done.

**Comment by mlenser** [comment]
@Alzam01 I started on this task - I've added a setting for switching between pounds and kgs. See https://app.roll20.net/forum/permalink/4099290/

I mention about expanding this to meters and feet.

Is this the kind of system you had in mind?

**Comment by Alzam01** [comment]
Yep, seems good for me :)

I guess you could do the same for feet/meters, but it's not really a high priority, considering that it's probably a little bit more work (you would have to change spell descriptions and stuff like that, seems tricky).

**Comment by mlenser** [comment]
Ya, it's a bit more tricky. I'll get there eventually, but have to focus on conversion stuff for now.

**Comment by Alzam01** [comment]
Btw, for the french rules, we assume that a pound is 1/2 kg for simplicity. Maybe you could use the same approximation ? Don't know for the other languages (don't even know if d&d was officially translated in another language).
(Sorry, I probably should have told you that before you made the changes)

**Comment by mlenser** [comment]
You could choose to do that manually and it may work at lower values, but when converting higher numbers the variance is far too much. For example 65 lb is ~29.5 kilos. If you used .5 then it'd be 32.5 which is 3 kilos different - rather important for determining how much you can carry.

**Comment by Orta15a** [comment]
Just to add a quick comment on that, if the carrying capacity use the same approximation than the weight of all objects, that does not make any difference really. I have been using 1 lb = 0.5kg for my games, for objects and carrying capacity of characters, and it worked without problem.

For the meters / feet problem, I stick with using feet, mostly because roll20 ruler is bugged when using not standard 5 feet grids. The feet metric is also included in some spells description texts, so a parsing method is necessary if the conversion is to be done.

**Comment by mlenser** [comment]
Closed as part of my new issue tracker via bitbucket
