### ISSUE TITLE
Add full translations for Italian

### ISSUE THREAD

**Issue by mlenser** [mlenser/roll20-character-sheets#134]
@00xeno00 there are some missing translations for Italian. Sheet version 4.0.0 will go live on Tuesday with the new translation system (built into roll20). If you want these on there it would be best to get them in before then. Otherwise we'll have to wait a week.

Let me know if I can be of any assistance. Here is the list that is missing:
HEAL_FOR
SAVE_FAILURE
SAVE_SUCCESS
SHOW_SPELL_LEVEL_IF_ALL_SLOTS_ARE_USED
SHOW_TOTALS
SHOW_UNPREPARED_SPELLS
TEXT_SIZE
VS

Overall you have pretty much everything except the last few additions. In this version the roll template will be translated as well so I'm sure that'll be helpful.

**Comment by 00xeno00** [comment]
Hi!

I'll add here the translation if that's okay with you, I'm not sure if I have the time to edit the thing myself, but let me know if it's too much of a bother and I'll try to find a moment.

Note: VS is the same for Italian, so it can stay as is.

"HEAL_FOR": "Cura di",
"SAVE_FAILURE": "Tiro salvezza fallito",
"SAVE_SUCCESS": "Tiro salvezza riuscito",
"SHOW_SPELL_LEVEL_IF_ALL_SLOTS_ARE_USED": "Mostra i livelli se tutti gli slot sono stati usati",
"SHOW_TOTALS": "Mostra totali",
"SHOW_UNPREPARED_SPELLS": "Mostra incantesimi non preparati",
"TEXT_SIZE": "Dimensione testo",

Thanks! Have a great weekend!

**Comment by mlenser** [comment]
Thanks! I'll add them.

**Comment by mlenser** [comment]
Oops forgot one:

"CRIT_DAMAGE_TOOLTIP": "Determines the damage to roll for a crit. Normal weapon damage is not included.",

This shows when a user hovers "crit" on damage for things like attacks.
Can you do that one as well?

**Comment by mlenser** [comment]
Also some others. Full list:

"CRIT_DAMAGE_TOOLTIP": "Determines the damage to roll for a crit. Normal weapon damage is not included.",
"FREEFORM": "Freeform",
"HIDE_NPC_INFO_NOTE": "Please see the documentation. You'll need to use a browser extension to change the css to show certain parts",
"HOUSERULES": "Houserules",
"OUTPUT": "Output",
"PERFORMANCE": "Performance",

**Comment by 00xeno00** [comment]
Freeform, Output and Performance can stay as is.

"CRIT_DAMAGE_TOOLTIP": "Determina il danno da tirare per un critico. Danno normale da arma non è incluso.",
"HIDE_NPC_INFO_NOTE": "Controllare la documentazione. È necessaria un'estenzione nel browser per cambiare il css per mostrare certe parti",
"HOUSERULES": "Regole personalizzate",

**Comment by mlenser** [comment]
Added

"CLASS_AND_LEVEL_PLACEHOLDER": "Generated after adding a class on the \"Character\" tab",

**Comment by mlenser** [comment]
This should be the last batch:

"CLASS_AND_LEVEL_PLACEHOLDER": "Generated after adding a class on the \"Character\" tab",
"DEATH_SAVING_THROW": "Death saving throw",
"DEATH_SAVING_THROWS": "Death saving throws",
"HIT_POINTS_TEMPORARY": "Temporary hit points",
"ABILITY_CHECK": "Ability check",
"PASSIVE_ABILITY_CHECK": "Passive ability check",
"COPPER_PIECES": "Copper pieces",
"SILVER_PIECES": "Silver pieces",
"ELECTRUM_PIECES": "Electrum pieces",
"GOLD_PIECES": "Gold pieces",
"PLATINUM_PIECES": "Platinum pieces",
"TOTAL_GOLD_VALUE": "Total gold value",
"HIT_POINTS_ROLLED": "Hit points rolled",
"AS": "as"

**Comment by 00xeno00** [comment]
"CLASS_AND_LEVEL_PLACEHOLDER": "Generati dopo aver aggiunto una classe
nella tab \"Personaggio\"",

"DEATH_SAVING_THROW": "Tiro salvezza vs morte",
"DEATH_SAVING_THROWS": "Tiri salvezza vs morte",
"HIT_POINTS_TEMPORARY": "Punti ferita temporanei",
"ABILITY_CHECK": "Prova di caratteristica",
"PASSIVE_ABILITY_CHECK": "Prova passiva di caratteristica",
"COPPER_PIECES": "Monete di rame",
"SILVER_PIECES": "Monete d'argento",
"ELECTRUM_PIECES": "Monete d'elettro",
"GOLD_PIECES": "Monete d'oro",
"PLATINUM_PIECES": "Monete di platino",
"TOTAL_GOLD_VALUE": "Valore totale in MO",
"HIT_POINTS_ROLLED": "Punti ferita tirati",
"AS": "come"

This should be the last batch:

"CLASS_AND_LEVEL_PLACEHOLDER": "Generated after adding a class on the
\"Character\" tab",
"DEATH_SAVING_THROW": "Death saving throw",
"DEATH_SAVING_THROWS": "Death saving throws",
"HIT_POINTS_TEMPORARY": "Temporary hit points",
"ABILITY_CHECK": "Ability check",
"PASSIVE_ABILITY_CHECK": "Passive ability check",
"COPPER_PIECES": "Copper pieces",
"SILVER_PIECES": "Silver pieces",
"ELECTRUM_PIECES": "Electrum pieces",
"GOLD_PIECES": "Gold pieces",
"PLATINUM_PIECES": "Platinum pieces",
"TOTAL_GOLD_VALUE": "Total gold value",
"HIT_POINTS_ROLLED": "Hit points rolled",
"AS": "as"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mlenser/roll20-character-sheets/issues/134#issuecomment-223809033>,
or mute the thread
<https://github.com/notifications/unsubscribe/AShp4Jz6qiciniBkJwORE-jSic2LQ9C2ks5qIrj8gaJpZM4IuG4m>
.

**Comment by mlenser** [comment]
I think you missed these:

"1_ACTION": "1 action",
"1_BONUS_ACTION": "1 bonus action",
"1_REACTION": "1 reaction",
"1_MINUTE": "1 minutes",
"10_MINUTES": "10 minutes",
"1_HOUR": "1 hour",
"8_HOURS": "8 hours",
"12_HOURS": "12 hours",
"24_HOURS": "24 hours",
"7_DAYS": "7 days",
"10_DAYS": "10 days",
"30_DAYS": "30 days",
"INSTANTANEOUS": "Instantaneous",
"UNTIL_DISPELLED": "Until dispelled",
"UNTIL_DISPELLED_OR_TRIGGERED": "Until dispelled or triggered",
"UP_TO_1_MINUTE": "up to 1 minute",
"1_ROUND": "1 round",
"UP_TO_1_ROUND": "up to 1 round",
"UP_TO_6_ROUNDS": "up to 6 rounds",
"UP_TO_10_MINUTES": "up to 10 minute",
"UP_TO_1_HOUR": "up to 1 hour",
"UP_TO_2_HOURS": "up to 2 hours",
"UP_TO_8_HOURS": "up to 8 hours",
"UP_TO_12_HOURS": "up to 12 hours",
"UP_TO_24_HOURS": "up to 24 hours",
"INSTANTANEOUS_OR_1_HOUR": "Instantaneous or 1 hour",
"SPECIAL": "Special",
"HALF_DAMAGE": "half damage",
"OR": "or",
"IF_THE_TARGET_IS": "If the target is",
"ARROWS": "Arrows",
"BITE": "Bite",
"DRAGON": "Dragon",
"LAWFUL_EVIL": "lawful evil",
"ONE_CREATURE": "one creature",
"AMPHIBIOUS": "Amphibious"

**Comment by 00xeno00** [comment]
Sorry, I was on my phone and gmail collapsed the whole thread so I missed those.

Here they are:

"1_ACTION": "1 azione",
"1_BONUS_ACTION": "1 azione bonus",
"1_REACTION": "1 reazione",
"1_MINUTE": "1 minuto",
"10_MINUTES": "10 minuti",
"1_HOUR": "1 ora",
"8_HOURS": "8 ore",
"12_HOURS": "12 ore",
"24_HOURS": "24 ore",
"7_DAYS": "7 giorni",
"10_DAYS": "10 giorni",
"30_DAYS": "30 giorni",
"INSTANTANEOUS": "Istantanea",
"UNTIL_DISPELLED": "Finché non è dissolto",
"UNTIL_DISPELLED_OR_TRIGGERED": "Finché non è dissolto o attivato",
"UP_TO_1_MINUTE": "fino a 1 minuto",
"1_ROUND": "1 round",
"UP_TO_1_ROUND": "fino a 1 round",
"UP_TO_6_ROUNDS": "fino a 6 round",
"UP_TO_10_MINUTES": "fino a 10 minuti",
"UP_TO_1_HOUR": "fino a 1 ora",
"UP_TO_2_HOURS": "fino a 2 ore",
"UP_TO_8_HOURS": "fino a 8 ore",
"UP_TO_12_HOURS": "fino a 12 ore",
"UP_TO_24_HOURS": "fino a 24 ore",
"INSTANTANEOUS_OR_1_HOUR": "Istantanea o 1 ora",
"SPECIAL": "Speciale",
"HALF_DAMAGE": "metà danni",
"OR": "o",
"IF_THE_TARGET_IS": "Se il bersaglio è",
"ARROWS": "Frecce",
"BITE": "Morso",
"DRAGON": "Drago",
"LAWFUL_EVIL": "legale malvagio",
"ONE_CREATURE": "una creatura",
"AMPHIBIOUS": "Anfibio"

**Comment by mlenser** [comment]
Thanks again
